### ISSUE TITLE
Add Google Authentication in Login Activity

### ISSUE THREAD

**Issue by VarunT11** [GeekHaven/ChatApp#1]
Add Google Authentication using Firebase in the Login Activity.

**Comment by siddhantdrk** [comment]
@starboi02  @VarunT11 can I work on this issue??

**Comment by phantom654** [comment]
may I work on this ?

**Comment by phantom654** [comment]
@starboi02 @VarunT11  may I work on this ?

**Comment by siddhantdrk** [comment]
@starboi02 can I work on it??

**Comment by Mandar16** [comment]
can I work on this ?

**Comment by VarunT11** [comment]
@siddhantdrk Sorry, but you can work on a single issue only in a particular repo. Once you complete a issue then only you can claim for other issue.

**Comment by VarunT11** [comment]
@Mandar16 Go ahead

**Comment by starboi02** [comment]
@Mandar16 what's the status?

**Comment by VarunT11** [comment]
@Mandar16 Since more than 2 days have passed after the issue was assigned to you, and since you have not created any PR, thus the issue is unassigned again.

**Comment by siddhantdrk** [comment]
can I work on this issue??

**Comment by VarunT11** [comment]
@siddhantdrk Go Ahead!

**Comment by siddhantdrk** [comment]
@VarunT11  can you add the SHA key below
SHA1: 89:52:D5:82:A5:30:EB:15:C7:FA:5E:09:FB:4E:99:ED:29:56:31:4E

**Comment by VarunT11** [comment]
@siddhantdrk Please provide your Google Account Email-Address so that I can provide you with the view-access to the Firebase Console.

**Comment by siddhantdrk** [comment]
Sure here's is my E-mail -siddhantdrk@gmail.com

**Comment by VarunT11** [comment]
@siddhantdrk I have added the SHA-1 Fingerprint and provided the access to the Firebase Console. You may proceed with your work.
