### ISSUE TITLE
Make Nav Header layout responsive

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/ChatApp#11]
The current nav header is hard coded :( 
By responsive it means use `wrap_content` instead of `dp` or `sp` .

**Comment by IC1101Virgo** [comment]
Can I work on this? :)

**Comment by VarunT11** [comment]
@IC1101Virgo Go Ahead

**Comment by starboi02** [comment]
@IC1101Virgo provide your SHA key so that we can add it to the firebase.

**Comment by IC1101Virgo** [comment]
@starboi02 Ok I'll do it. 💯

**Comment by Devildarkfire** [comment]
I want to work on this

**Comment by starboi02** [comment]
@IC1101Virgo what's the status ? if you are unable to make a PR by today this issue will be assigned to @Devildarkfire .

**Comment by IC1101Virgo** [comment]
@starboi02 Hey Varun! I am working on it, actually it's the first time I have tried this that's why its taking time. Can you give me till 9 PM?  If I am unable to do it by then please assign it to others 😄 
Thank you!

**Comment by starboi02** [comment]
@IC1101Virgo ok sure take your time and send it by tomorrow morning.
