### ISSUE TITLE
Add a User Class

### ISSUE THREAD

**Issue by VarunT11** [GeekHaven/ChatApp#12]
Add a User.java file which should contain the following details:
1. Username
2. Display Name
3. Email Address
4. Auth UID
5. Date of Birth
6. Gender
7. Type of Account (Public or Private)
8. Profile Photo

Use proper name and data types for the above attributes and create getter and setter for each one of them. Make sure that the Data Type of Profile Photo is URI. Also create a constructor with Auth UID as the parameter.
Use the concept of Enums where the value of the Attribute is fixed or is among some particular choices.

**Comment by deepak-gup7a** [comment]
Can I work on this issue??

**Comment by VarunT11** [comment]
@deepakgupta124 Go Ahead!

**Comment by deepakgupta124** [comment]
#13 User.java file added
