### ISSUE TITLE
Add Splash Screen to App

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/ChatApp#16]
`logo_splash_screen.png` is provided in the drawable folder. Use `white` color for background of Splash Screen.

**Comment by Mandar16** [comment]
I would like to work on this

**Comment by VarunT11** [comment]
@Mandar16 Go Ahead!

**Comment by starboi02** [comment]
@Mandar16 how many PRs have you submitted yet.

**Comment by Mandar16** [comment]
5 pr's

**Comment by starboi02** [comment]
Well, nice that means you are left with only 1 PR so no more issues would be assigned to you unless no one claims them for days :)

**Comment by starboi02** [comment]
this issue if free for grab now!

**Comment by DevilAJ** [comment]
Can I work on this issue.

**Comment by starboi02** [comment]
@DevilAJ go ahead
