### ISSUE TITLE
Check whether User exists or not in the Firebase Realtime Database and Navigate accordingly

### ISSUE THREAD

**Issue by VarunT11** [GeekHaven/ChatApp#17]
After Successful Authentication of the User in LoginActivity.java, check whether the Authenticated User exists or not in the Firebase Realtime Database. You first need to integrate Firebase Realtime Database in the Application.
Registered User's detail would be stored at the following reference : root -> user -> _(User UID)_
Use a different static class named FirebaseHandler.java to handle all Firebase Related Events. You should implement the above function in this class only. Use the concept of enums to define the Keys of the Database.
If the user is already registered then navigate to MainActivity.java directly else navigate to RegisterActivity.java

**Comment by Pranshu-Tripathi** [comment]
Can i Work on this ?

**Comment by starboi02** [comment]
@Pranshu-Tripathi go ahead

**Comment by starboi02** [comment]
@Pranshu-Tripathi feel free to ask either me or @VarunT11 if you get stuck anywhere.

**Comment by VarunT11** [comment]
@Pranshu-Tripathi Provide me your Google Account Email-Address linked with Firebase so that I can provide you with the view-access of the Firebase Console.

**Comment by Pranshu-Tripathi** [comment]
@VarunT11 mail id : mtpranshu2001@gmail.com

**Comment by VarunT11** [comment]
@Pranshu-Tripathi I have provided you the view-access of the Firebase Console, you may proceed with your work!

**Comment by Pranshu-Tripathi** [comment]
@VarunT11  I am still unable to sign in using mtpranshu2001@gmail.com using google signin .. Please see into it.

**Comment by Pranshu-Tripathi** [comment]
SHA1: 45:29:8C:8B:1F:13:B6:9C:E7:53:85:BA:2B:8F:7B:9A:5B:68:35:8B
SHA KEY

**Comment by starboi02** [comment]
@Pranshu-Tripathi what's the status?

**Comment by Pranshu-Tripathi** [comment]
Working on it ... will close the issue by tomorrow max .
