### ISSUE TITLE
Add Navigation Drawer in Main Activity

### ISSUE THREAD

**Issue by VarunT11** [GeekHaven/ChatApp#2]
Add the Navigation Drawer in the Main Activity with the following components:
* My Profile
* Chat List
* Find Friends
* Settings
* Logout

**Comment by sanchi0204** [comment]
Can I work on this?

**Comment by siddhantdrk** [comment]
@starboi02  I would like to work on this.😃

**Comment by starboi02** [comment]
@sanchi0204 we are sorry to inform you that this is our college event and we are not entertaining any PRs outside the college domain due to shortage of issues :(

**Comment by siddhantdrk** [comment]
@starboi02  @VarunT11  I would like to work on this issue.

**Comment by starboi02** [comment]
@siddhantdrk go ahead!

**Comment by starboi02** [comment]
@siddhantdrk add your contribution to https://github.com/GeekHaven/Geektoberfest-Main if you haven't.
