### ISSUE TITLE
Implement design from figma link

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/ChatApp#26]
Make an onboarding page with design https://www.figma.com/file/78nSdj97RVUJqB81j1genU/Vibsey?node-id=0%3A1   ``X-1`` and move to login page on clicking continue.

**Comment by deepak-gup7a** [comment]
Can I make above design ?

**Comment by starboi02** [comment]
@deepakgupta124 go ahead!

**Comment by deepak-gup7a** [comment]
@starboi02  please review and suggest if any changes are required ..
