### ISSUE TITLE
Move email authentication to new screen

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/ChatApp#27]
Currently email notification is on Login page, new email auth page should be opened when clicked on email auth from login screen.
Also implement ``X-2`` design to Login page.
Ref: https://www.figma.com/file/78nSdj97RVUJqB81j1genU/Vibsey?node-id=3%3A9

**Comment by deepak-gup7a** [comment]
@starboi02  can I work on above issue??

**Comment by starboi02** [comment]
@deepakgupta124 go ahead.

**Comment by deepak-gup7a** [comment]
hey @starboi02  please review my pull request and suggest if any changes needed.
