### ISSUE TITLE
Add Navigation Header in the Navigation Bar

### ISSUE THREAD

**Issue by VarunT11** [GeekHaven/ChatApp#4]
Add Navigation Header with a proper drawable for User Image and TextView for User Name in the Navigation Bar of Main Activity

**Comment by kumar0500** [comment]
Hi VarunT11, I am interested to work on this. Can this be assigned to me?
Thank you!

**Comment by starboi02** [comment]
@kumar0500 sorry to inform you as this is a college event no outside PRs would be entertained.

**Comment by CadencePrestissimo** [comment]
I would like to do this

**Comment by VarunT11** [comment]
@CadencePrestissimo Sure! Go Ahead
