### ISSUE TITLE
Add suitable icons to navigation drawer components

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/ChatApp#5]
For any doubts join Discord channel of GeekTober provided in the GeekHaven mail.

**Comment by CadencePrestissimo** [comment]
I
 would like to do this

**Comment by VarunT11** [comment]
@CadencePrestissimo Sorry, but you can work on a single issue only in a particular repo. Once you complete a issue then only you can claim for other issue.

**Comment by JLodha** [comment]
I want to work on this issue.

**Comment by VarunT11** [comment]
@JLodha Sure! Go Ahead

**Comment by DevilAJ** [comment]
I want to work on this issue.

**Comment by DevilAJ** [comment]
I want to work on this issue.

**Comment by starboi02** [comment]
@DevilAJ @JLodha is currently working on it so if he's unable to do it after 2 days from the issue opening date it will be assigned to you.

**Comment by DevilAJ** [comment]
Ok
